### ISSUE TITLE
Head scripts are reappended and reexecuted on navigation

### ISSUE THREAD

**Issue by guanzo** [nuxt/vue-meta#381]
### Version

[2.7.1](https://github.com/nuxt.js/releases/tag/2.7.1)

### Reproduction link

[https://github.com/guanzo/codesandbox-nuxt](https://github.com/guanzo/codesandbox-nuxt)

### Steps to reproduce

```
$ git clone https://github.com/guanzo/codesandbox-nuxt nuxtbug
$ cd nuxtbug
$ npm i
$ npm run generate
$ npx http-server dist
```
Open the webpage and dev tools, go to the Elements tab, expand the ` <head>` node

Note the position of the element
```
<script data-n-head="true" src="https://arc.io/widget.js?MURGrEjPmB6gVvzyvpbDut" async=""></script>
```

Note the element `<div id="arc-widget"></div>` at the bottom of `<body>`. This element is created when the `arc.io/widget.js` script is loaded.

Click the "test" link

The `<head>` is updated and the script has been appended to the bottom of  `<head>`, causing it to execute again, and now there are 2 `#arc-widget` elements.

### What is expected ?

A script is loaded once across all navigations.

### What is actually happening?

A script is loaded twice across all navigations.

### Additional comments?

Related to https://github.com/nuxt/nuxt.js/issues/3396.

This only occurs when each nuxt page has its own title. When nuxt updates the page title on navigation, the script is reappended. The `hid` attribute on the script tag doesn't fix it.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9269">#c9269</a>)</em></sub></div>

**Comment by pimlie** [comment]
Transferred this to vue-meta repo as it appears to be a vue-meta bug indeed.

More strangely, apparantly I even deliberately 'fixed' the tests to include this difference: https://github.com/nuxt/vue-meta/blob/master/test/utils/meta-info-data.js#L127

Will have a look tomorrow whether that was just a brain fart or that there was more to it.

**Comment by pimlie** [comment]
This should be fixed now. Seemed to just have been an oversight, not a brain fart as so much ;)

**Comment by snapwich** [comment]
Hi @pimlie,

After much struggle I've decided with about 99% certainty that this bug is what is causing this other bug: https://github.com/nuxt-community/google-adsense-module/issues/16

The google adsense code placed in the head is ran once in dev mode but with `nuxt generate` code it runs once on load and once when navigating to another page but then no more after that.  Running twice in those situations breaks the adsense module for pages rendered from `nuxt generate`

I used yarn to resolve `vue-meta`  to `2.0.3` (latest) and confirmed that `window.$nuxt._vueMeta` exists and is an object but the problem still exists.  If this is the same bug (which I think it is) then I don't think it has been fixed.

**Comment by amritk** [comment]
Hmm I think I'm running into this issue right now with nuxt build --spa. Was the fix released?

**Comment by bengineer19** [comment]
@snapwich I agree.

I initially had the issue with `npm run dev` but after updating nuxt, everything now works fine in dev mode (and also `npm run build && npm run start`). However when statically generating using `npm run generate`, the problem still occurs.
