### ISSUE TITLE
[Version `3.0.0-alpha.9`] Typescript Error 6053

### ISSUE THREAD

**Issue by Penguinlay** [nuxt/vue-meta#693]
# Typescript Error 6053

```node
node_modules/vue-meta/dist/vue-meta.d.ts:9:22 - error TS6053: File '/Users/shein/kk/gh/reproduction-vueMetaTypescriptError6053/node_modules/vue-meta/dist/ssr.d.ts' not found.

9 /// <reference path="ssr.d.ts" />
                       ~~~~~~~~
```

# Issue

https://github.com/nuxt/vue-meta/blob/eec4e7c7c00dfff74edd29675421052596bbada1/dist/vue-meta.d.ts#L9

# Minimal Reproduction

https://github.com/Penguinlay/reproduction-vueMetaTypescriptError6053

# Additional Details

## Dependencies

```json
"dependencies": {
  "vue": "3.1.1",
  "vue-meta": "3.0.0-alpha.9"
},
"devDependencies": {
  "@vitejs/plugin-vue": "1.2.3",
  "@vue/compiler-sfc": "3.1.1",
  "typescript": "4.4.0-dev.20210617",
  "vite": "2.3.7",
  "vue-tsc": "0.1.7"
}
```

# P.S.

I have not tested it with Vue Meta versions other than `3.0.0-alpha.9` and dependencies' versions other than those listed above.

**Comment by Penguinlay** [comment]
I am not that familiar with implementing `d.ts`, and I'm quite occupied these days. So, if anyone wants to take on this project, please feel free to do so!

**Comment by pimlie** [comment]
Thanks, I linked the wrong file here indeed. Should be fixed with this commit https://github.com/nuxt/vue-meta/commit/ef3b51a74c824f929ed81e63549618a35d72f2fb

**Comment by ApolloNet** [comment]
`/dist/vue-meta.d.ts` should also be fixed :)

**Comment by Penguinlay** [comment]
> Thanks, I linked the wrong file here indeed. Should be fixed with this commit [ef3b51a](https://github.com/nuxt/vue-meta/commit/ef3b51a74c824f929ed81e63549618a35d72f2fb)

Sounds great! You can link this issue to that PR and close this. Thank you so much!

**Comment by grindarius** [comment]
Hello, has the fix been published to npm yet? Since I still get the problem using `vue-meta@3.0.0-alpha.9`. Is there any version I could roll back to solve the problem? Thank you.

**Comment by davidnknight** [comment]
Also waiting for this to be merged and a new release tagged. Currently it's causing builds to fail in our Vite/Vue app which requires Vue 3 and TS support.

**Comment by thinkriver** [comment]
This issue is still happening in 3.0.0-alpha.9, causing build error.

**Comment by mgiraldo** [comment]
same problem here. i had to modify the type definition file by hand as described by @pimlie

**Comment by jamesalways** [comment]
can you publish a version with this fix?

**Comment by mgiraldo** [comment]
i'd do a PR with this specific change but i'm unsure if it affects anything else?

**Comment by Penguinlay** [comment]
> i'd do a PR with this specific change but i'm unsure if it affects anything else?

That relative path update should fix this issue. Link this issue and PR it!

**Comment by Penguinlay** [comment]
Hmm, it seems the fix is already up on this next branch via #723. Perhaps it just needs to be published to npm.

**Comment by mgiraldo** [comment]
oh i see... it is a matter of publishing this fixed file to npm. it is already fixed in the repo 🤔

**Comment by jamesalways** [comment]
Please, can you publish a new version in NPM? We need this fixed! Thanks!

**Comment by mgiraldo** [comment]
can someone @nuxt please give this a look? it is a matter of publishing the package to npm

**Comment by jamesalways** [comment]
Please, someone can publish this?

**Comment by ibrahimmenem** [comment]
yes please :pray: :pray:

**Comment by mgiraldo** [comment]
please?

**Comment by jamesalways** [comment]
@Atinux @pimlie @zspecza @manniL can you help us with this?

**Comment by danielroe** [comment]
New version should be released including this fix: `3.0.0-alpha.10`. 😊

**Comment by jamesalways** [comment]
Thanks!!!!! ^^ 🥳

**Comment by mgiraldo** [comment]
i can confirm this being fixed. thanks!
